Algoritmo "CalculoAreaCircunferencia"
// Disciplina  : [Linguagem de Programação com JavaScript]
// Professor   : Jailsom Costa Santos
// Descrição   : Solicita o valor do raio e efetue o valor da area da circunferencia
// Autor(a)    : Guilherme
// Data atual  : 29/03/2022
Var
// Seção de Declarações das variáveis 
raio,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o valor da circunferencia:")
Leia(raio)
//forms de solução
area<-pi*raio*raio
Escreval("O calculo da area é igual: " ,area)
Fimalgoritmo
