Algoritmo "Dividir"
// Disciplina  : [Linguagem de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar dois valores e exibir o resultado
// Autor(a)    : Guilherme
// Data atual  : 24/03/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro
dividir:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Boa Noite turma do ADS")
Escreva("Digite um número:")
Leia(numero1)
Escreval("Digite um número:")
Leia(numero2)
dividir<-numero1/numero2
Escreval("A divisão dos valores digitados é:",dividir)

Fimalgoritmo
