Algoritmo "ExemploEscolhacaso"
// Disciplina  :[Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Exemplo meses do ano
// Autor(a)    : Guilherme Garoli
// Data atual  : 18/04/2022
Var
   // Seção de Declarações das variáveis
   letra:caracter

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite uma letra")
   Leia(letra)

   Escolha letra
   caso "A"
      Escreval("Janeiro")
   caso "b"
      Escreval("Fevereiro")
   caso "c"
      Escreval("Março")
   caso "d"
      Escreval("Abril")
   caso "e"
      Escreval("Maio")
   caso "f"
      Escreval("Junho")
   caso "g"
      Escreval("Julho")
   caso "h"
      Escreval("Agosto")
   caso "i"
      Escreval("Setembro")
   caso "j"
      Escreval("Outubro")
   caso "k"
      Escreval("Novembro")
   caso "l"
      Escreval("Dezembro")
   outrocaso
   Escreval("Não existe mês correspondente")
   fimescolha
Fimalgoritmo