Algoritmo "ExemploContadora"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// enquanto contadora<10 faca
// Escreval("Lelis")
//   contadora<-contadora+1
//  fimenquanto

// criação de um laço de repetição
 enquanto contadora<8 faca
   Escreval("Contadora")
   contadora<-contadora+1
 fimenquanto
Fimalgoritmo