Algoritmo "Exercicio06ManzanoLacopara"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 02/05/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para contadora de 1 ate 199 passo 1 faca
      se contadora %4=0 entao
         Escreval(contadora)
      fimse
   fimpara


Fimalgoritmo
Apresentar  todos  os  números  divisíveis  por  4  que  sejam  menores  que  200.  Para  verificar  se  o
número  é  divisível  por  4,  efetuar  dentro  da  malha  a  verificação  lógica  desta  condição  com  a
instrução  se,  perguntando  se  o  número  é  divisível;  sendo,  mostre-o;  não  sendo,  passe  para  o
próximo passo. A variável que controlará o contador deve ser iniciada com o valor 1.