Algoritmo "Exercicio01ManzanoLacopara"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 02/05/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 15 ate 200 passo 2 faca
      Escreval ("o quadrado : " ,contadora, " é igual a : " ,contadora*contadora)
   fimpara

Fimalgoritmo
