Algoritmo "Exercicio02ManzanoLacopara"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 02/05/2022
Var
   // Seção de Declarações das variáveis
   resultado,numero,contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o numero da tabuada que deseja saber:")
   Leia(numero)
   para contadora de 1 ate 10 passo 1 faca
      resultado<-contadora*numero
      Escreval(numero, " X " , contadora, " = " ,resultado)
   fimpara
   
Fimalgoritmo
