Algoritmo "Exercicio04LacoEnquantoManzano"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio04LacoEnquantoManzano
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora<-1
   enquanto contadora<21 faca
      se contadora%2 =1 entao
         Escreval("Os numero impar é" ,contadora)
      fimse
      contadora<-contadora+1

   fimenquanto


Fimalgoritmo