algoritmo "Exercicio19Faccat"
var
   numero1, numero2:inteiro
inicio
   Escreval("Digite um número :")
   Leia(numero1)
   Escreval("Digite um número :")
   Leia(numero2)

   se numero1>numero2 entao
      Escreval("O número 1, que é :",numero1," é maior que o número 2, que é:", numero2)
   senao
      Escreval("O número 2, que é:", numero2," é maior que o número 1, que é :", numero1)
   fimse
fimalgoritmo