Algoritmo "Exercicio01LacoRepita"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis

   contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora<-15
   repita
      Escreval("O valor do quadrado do número " ,contadora, "corresponde á :" , contadora*contadora)
      contadora<-contadora+1
   ate contadora>200
Fimalgoritmo