Algoritmo "Exercicio06LacoEnquantoManzano"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio06LacoEnquantoManzano
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis
   numero,numero2:inteiro
   resultado:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um numero")
   Leia(numero)
   Escreval("Digite outro numero")
   Leia(numero2)
   resultado<-exp(numero,numero2)
   Escreval("O expoente de " , numero," elevado á ",numero2, " é: " , resultado)

Fimalgoritmo