Algoritmo "Exercicio04ManzanoLacopara"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 02/05/2022
Var
   // Seção de Declarações das variáveis
   acumuladora,contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para contadora de 1 ate 500 passo 1 faca
      se contadora %2=0 entao
         acumuladora<-acumuladora+contadora
      fimse
   fimpara
   Escreval(acumuladora)

Fimalgoritmo
