Algoritmo "Exercicio01LacoEnquantoManzano"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio01LacoEnquantoManzano
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis
   numero:inteiro
   resultado:inteiro
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora<-1
   Escreval("Digite um numero:")
   Leia(numero)
      enquanto contadora<11 faca
      resultado<-numero*contadora
      Escreval(numero, " x ",contadora, " = " , resultado)
      contadora<-contadora+1

   fimenquanto

Fimalgoritmo