Algoritmo "Exercicio02LacoEnquantoManzano"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio02LacoEnquantoManzano
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis
   soma:inteiro
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora<-1
      enquanto contadora<101 faca
      soma <-soma+contadora
      contadora<-contadora+1
       fimenquanto
   Escreval("O valor da soma corresponde a:",soma)
Fimalgoritmo