Algoritmo "Exercicio05LacoEnquantoManzano"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio05LacoEnquantoManzano
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro
   resultado:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora<-1
   enquanto contadora<16 faca
    resultado<-exp(3,contadora)
   Escreval("O expoente de 3 elevado á:" ,contadora, " é " ,resultado)
      contadora<-contadora+1
   fimenquanto

Fimalgoritmo